smart_kit/compatibility/commands.py, tests/smart_kit_tests/compatibility/test_commands.py
pass the auto-listening field explicitly and fix the auto-listening logic priority
=> fix auto-listening

setup.py
add license, change author and description
=> add license

core/basic_models/requirement/basic_requirements.py, setup.py, tests/core_tests/requirements_test/test_requirements.py
- избавился от freezegun
- правильно работаю с offset
- перевожу timestamp в datetime
- сравниваю только время без даты
=> fix time requirement

.github/workflows/python-publish-to-pip.yml
=> fetch all tags

core/basic_models/requirement/basic_requirements.py, setup.py, smart_kit/resources/__init__.py, tests/core_tests/requirements_test/test_requirements.py
=> add date requirement

smart_kit/start_points/main_loop_kafka.py
add route_kafka_broker setting
=> add route_kafka_broker setting

smart_kit/start_points/main_loop_kafka.py
=> - fix log;

smart_kit/action/http.py
fix behavior.timeout usage in HTTPRequestAction
=> fix behavior.timeout usage in HTTPRequestAction

core/basic_models/requirement/basic_requirements.py, scenarios/scenario_models/field/field_filler_description.py, smart_kit/resources/__init__.py, tests/core_tests/requirements_test/test_requirements.py
=> intersection requirement

smart_kit/template/app/basic_entities/actions.py-tpl, smart_kit/template/app/basic_entities/requirements.py-tpl
=> fix basic templates

smart_kit/template/wsgi.py-tpl
Fix wsgi.py template: add missed `log_const` in import
=> Fix wsgi.py template: add missed "log_const" in import

core/unified_template/unified_template.py
позволяет добавлять всякие доп фичи, типа jinja2.ext.do
=> added jinja extensions

scenarios/actions/action.py, smart_kit/resources/__init__.py, tests/scenarios_tests/actions_test/test_action.py
- Added universal action class `ChoiceScenarioAction ` in order to choice scenario if requirement is met.   
- Added unit-tests for new functionality.
=> Add universal `ChoiceScenarioAction` to choice from multiple scenarios

smart_kit/testing/local.py
Load predefined_fields_storage once, when local testing starts
=> Load predefined_fields_storage once, when local testing starts

smart_kit/template/static/references/forms/hello_form.json
Add missed `"type": "question"` for "book_is_read" in hello form
=> Add missed `"type": "question"` for "book_is_read" in hello form

smart_kit/testing/local.py, smart_kit/testing/suite.py
pause between messages when running test files from local_testing
=> pause between messages when running test files from local_testing

README.md
I edited python version because python 3.7.9 is not compatible with the project.
=> README requirements fix

smart_kit/testing/local.py
Fix local testing if not predefined_fields_storage file
=> Fix local testing if there's no predefined_fields_storage file

scenarios/scenario_descriptions/form_filling_scenario.py, scenarios/scenario_models/field/field_descriptions/basic_field_description.py
=> fixes for fields and forms

smart_kit/action/http.py
Add headers validation when http_request action
=> Add headers validation when http_request action

README.md
Fix telegram chat link in Readme file
=> Fix telegram chat link in Readme file

scenarios/actions/action.py
=> fix underscore typo

smart_kit/management/tests.py, smart_kit/testing/suite.py
CSV-файл содержит колонки для имени файла теста, названия теста и базового результата прогона - 1(успех) и 0 (провал)
=> Добавлен ключ создания csv-файла для базовых результатов прогона тестов

smart_kit/testing/suite.py, smart_kit/utils/diff.py
Теперь csv генерируется стандартной библиотекой и в отдельном поле имеет информацию об отличиях, сериализованную в JSON
=> Более подробная информация о результатах тестирования

core/db_adapter/redis_adapter.py
fix _replace_if_equals in redis_adapter.py
=> fix _replace_if_equals in redis_adapter.py

smart_kit/start_points/main_loop_http.py
=> add status handler

setup.py
=> bump aiohttp version

setup.py
=> fix aioredis version

smart_kit/request/kafka_request.py, smart_kit/start_points/main_loop_kafka.py
Появилась возможность добавления дополнительных заголовков в kafka-запросы и логирование заголовков kafka-запросов
=> kafka extra headers option and logging added

core/utils/masking_message.py
add values to card masking fields
=> add values to card masking fields

scenarios/scenario_models/field/field_filler_description.py
Исправлена логика заполнения филлера
=> fix DatePeriodFiller

smart_kit/handlers/handler_text.py
Text preprocessing result wasn't logged
=> Fix text preprocessing result logging in HandlerText

core/basic_models/actions/push_action.py, core/basic_models/actions/string_actions.py, smart_kit/message/smart_app_push_message.py, smart_kit/resources/__init__.py, smart_kit/start_points/main_loop_kafka.py, smart_kit/template/static/configs/template_config.yml, tests/core_tests/basic_scenario_models_test/action_test/test_action.py, tests/smart_kit_tests/message/test_smart_app_push_message.py
Добавил экшен по отправке пушей в сервер нотификаций.
=> PNLP-2720 added push notify and test

core/basic_models/actions/client_profile_actions.py, tests/core_tests/requirements_test/test_requirements.py
- Добавлена возможность задавать kafka_key для client_profile в конфиге или в параметрах экшна
- Добавлен опциональный параметр protocolVersion
=> improve client_profile_actions

smart_kit/action/base_http.py, tests/smart_kit_tests/action/test_base_http_action.py
- Добавил доп параметры в логи rest запроса, чтобы можно было их переопределять
- Дополнил проверку хэдэров: если значние хэдера строка или байты - оставляем неизменным, если int, float, bool - приводим к строке, иначе вырезаем. То есть теперь если в хэдеры попадает объект - он вырезается
=> DPNLPF-1536 added additional params for logging and improve headers checks

smart_kit/template/static/references/actions/actions.json
Problem: smart_app_framework/core/basic_models/requirement/basic_requirements.py", line 140, in __init__
self._template = UnifiedTemplate(items["template"])
KeyError: 'template'
Fix: add field template
=> fix template error

scenarios/actions/action.py, scenarios/requirements/requirements.py, smart_kit/resources/__init__.py, tests/scenarios_tests/actions_test/test_action.py
Удалён AskAgainAction, AskAgainExistRequirement  переделан в соответсвии с новым форматом переспросов
=> DPNLPF-1554 remove AskAgainAction

smart_kit/template/app/resources/custom_app_resourses.py-tpl, smart_kit/testing/suite.py
Пофиксил импорты которые сломались при переносе импортов к модуле конфиг внутрь функции get_app_config
=> Bugfix: fix imports

smart_kit/configs/__init__.py, smart_kit/start_points/app.py, smart_kit/start_points/base_main_loop.py, smart_kit/start_points/main_loop_async_http.py, smart_kit/start_points/main_loop_http.py, smart_kit/start_points/main_loop_kafka.py, smart_kit/start_points/postprocess.py
Добавил постпроцессор.
Это нужно для того, чтобы после обработки каждого сообщения можно совершать какие нибудь действия. 
Постпроцессор можно переопределить в app_config:
in `app/postprocessor.py`
```python
from smart_kit.start_points.postprocess import PostprocessMainLoop
class CustomPostprocess(PostprocessMainLoop):
def postprocess(self, user, message, *args, **kwargs):
...
```
in `app_config.py`
```python
from app.postprocessor import CustomPostprocess
...
POSTPROCOESSOR_MAIN_LOOP = CustomPostprocess
```
Так же можно объединить несколько постпроцессоров в один (это может быть нужно например когда используете несколько плагинов одновременно):
```python
from smart_kit.start_points.postprocess import postprocessor_compose
POSTPROCOESSOR_MAIN_LOOP = postprocessor_compose(Processor1, …
```
=> added postprocessor
